/**
 * Karachi-tuned care profile seed data (Data layer, L2) — TODO T-039.
 * Covers the current collection (PROJECT_REQUIREMENTS.md §1.1). Watering
 * intervals are days between waterings per care season
 * (config/climate.karachi.js); users can edit or override per plant.
 *
 * Horticultural rationale is embedded in the notes so future readers know
 * WHY, not just what. Reviewed like code (CONTRIBUTING.md §7).
 */

export const KARACHI_CARE_PROFILES = [
  {
    name: 'Plumeria (Karachi)',
    species: 'Plumeria',
    wateringSeasonal: { summer: 3, monsoon: 7, winter: 10 },
    fertilizeEveryDays: 21,
    fertilizer: 'Low-N, high-P bloom fertilizer (e.g. 10-30-10) during Mar–Sep',
    repotEveryMonths: 24,
    pruningNotes: 'Prune in late winter before flush; cuttings root easily (propagation).',
    seasonalNotes: {
      heatWave: 'Established plumeria shrug off heat; water potted ones in the evening.',
      monsoon: 'Watch for plumeria rust (orange pustules under leaves) — remove affected leaves, improve airflow, stop overhead watering.',
    },
    source: 'seed',
  },
  {
    name: 'Bougainvillea (Karachi)',
    species: 'Bougainvillea',
    wateringSeasonal: { summer: 2, monsoon: 8, winter: 6 },
    fertilizeEveryDays: 30,
    fertilizer: 'Balanced with micronutrients; slight drought stress triggers blooming',
    repotEveryMonths: 36,
    pruningNotes: 'Cut back hard after each bloom flush; blooms on new growth.',
    seasonalNotes: {
      heatWave: 'Thrives in Karachi heat; do not overwater — heat + wet roots = leaf drop.',
      monsoon: 'Reduce watering sharply; ensure pots drain freely or roots rot.',
    },
    source: 'seed',
  },
  {
    name: 'Rose — desi (Karachi)',
    species: 'Rosa',
    wateringSeasonal: { summer: 1, monsoon: 3, winter: 2 },
    fertilizeEveryDays: 15,
    fertilizer: 'Alternate organic (compost/gobar) with balanced NPK; stop in peak June heat',
    repotEveryMonths: 24,
    pruningNotes: 'Main prune late December; deadhead constantly for repeat bloom.',
    seasonalNotes: {
      heatWave: 'Morning water + afternoon shade cloth; June flowers will be small — normal.',
      monsoon: 'Blackspot season: remove fallen leaves, spray neem preventively.',
    },
    source: 'seed',
  },
  {
    name: 'Jasmine / Motia (Karachi)',
    species: 'Jasminum sambac',
    wateringSeasonal: { summer: 1, monsoon: 4, winter: 4 },
    fertilizeEveryDays: 30,
    fertilizer: 'Balanced NPK Mar–Sep; motia blooms best with steady summer moisture',
    repotEveryMonths: 24,
    pruningNotes: 'Prune in February — flowers come on new season growth.',
    seasonalNotes: {
      heatWave: 'Peak motia season; do not let pots dry out on 40°C days.',
      monsoon: 'Budworm caterpillars appear — check unopened buds for holes.',
    },
    source: 'seed',
  },
  {
    name: 'Tulsi (Karachi)',
    species: 'Ocimum tenuiflorum',
    wateringSeasonal: { summer: 1, monsoon: 3, winter: 2 },
    fertilizeEveryDays: 30,
    fertilizer: 'Light compost tea; heavy feeding weakens aroma',
    repotEveryMonths: 12,
    pruningNotes: 'Pinch flower spikes to keep leaf production; harvest tops often.',
    seasonalNotes: {
      heatWave: 'Wilts fast in pots — may need morning AND evening water.',
      monsoon: 'Prone to fungal wilt in waterlogged soil; raise pots off the floor.',
    },
    source: 'seed',
  },
  {
    name: 'Boston Fern (Karachi)',
    species: 'Nephrolepis exaltata',
    wateringSeasonal: { summer: 1, monsoon: 2, winter: 3 },
    fertilizeEveryDays: 30,
    fertilizer: 'Quarter-strength balanced liquid feed',
    repotEveryMonths: 18,
    pruningNotes: 'Trim browned fronds at the base; divide when root-bound.',
    seasonalNotes: {
      heatWave: 'Keep out of hot dry wind; mist or group plants to raise humidity.',
      monsoon: 'Loves monsoon humidity — best season; just avoid standing water.',
    },
    source: 'seed',
  },
  {
    name: 'Palm — Areca / Lady / Malaysian (Karachi)',
    species: 'Dypsis lutescens / Rhapis excelsa',
    wateringSeasonal: { summer: 2, monsoon: 4, winter: 5 },
    fertilizeEveryDays: 45,
    fertilizer: 'Palm mix with Mg + micronutrients; browning tips often = salty water — flush pots monthly',
    repotEveryMonths: 30,
    pruningNotes: 'Remove only fully brown fronds; green-tipped fronds still feed the palm.',
    seasonalNotes: {
      heatWave: 'Bright indirect light indoors; scorches in direct summer sun.',
      monsoon: 'Check for spider mite explosions when brought indoors to AC rooms.',
    },
    source: 'seed',
  },
  {
    name: 'Snake Plant (Karachi)',
    species: 'Dracaena trifasciata',
    wateringSeasonal: { summer: 7, monsoon: 14, winter: 20 },
    fertilizeEveryDays: 60,
    fertilizer: 'Half-strength balanced, growing season only',
    repotEveryMonths: 36,
    pruningNotes: 'Remove rotted leaves at soil line; divide rhizomes to propagate.',
    seasonalNotes: {
      heatWave: 'Utterly unbothered. The cockroach of houseplants (affectionately).',
      monsoon: 'The killer month: humidity slows drying — when in doubt, don\'t water.',
    },
    source: 'seed',
  },
  {
    name: 'Money Plant / Pothos (Karachi)',
    species: 'Epipremnum aureum',
    wateringSeasonal: { summer: 3, monsoon: 5, winter: 7 },
    fertilizeEveryDays: 45,
    fertilizer: 'Any balanced liquid feed at half strength',
    repotEveryMonths: 24,
    pruningNotes: 'Cut leggy vines above a node; root cuttings in water.',
    seasonalNotes: {
      heatWave: 'Fine indoors; outdoor plants need shade from afternoon sun.',
      monsoon: 'Grows fastest now; support or trim the surge.',
    },
    source: 'seed',
  },
  {
    name: 'Rubber Plant (Karachi)',
    species: 'Ficus elastica',
    wateringSeasonal: { summer: 4, monsoon: 7, winter: 10 },
    fertilizeEveryDays: 45,
    fertilizer: 'Balanced feed in growing season; wipe leaves monthly for photosynthesis',
    repotEveryMonths: 30,
    pruningNotes: 'Cut above a node to branch; sap is latex — wear gloves.',
    seasonalNotes: {
      heatWave: 'Tolerates heat in bright shade; sudden leaf drop = moved or overwatered.',
      monsoon: 'Let the top 5 cm dry between waterings regardless of schedule.',
    },
    source: 'seed',
  },
  {
    name: 'Dieffenbachia (Karachi)',
    species: 'Dieffenbachia',
    wateringSeasonal: { summer: 3, monsoon: 5, winter: 7 },
    fertilizeEveryDays: 45,
    fertilizer: 'Half-strength balanced, monthly in growing season',
    repotEveryMonths: 24,
    pruningNotes: 'Sap is irritant — gloves. Cane cuttings propagate easily.',
    seasonalNotes: {
      heatWave: 'Keep in bright shade; leaf edges burn in dry heat.',
      monsoon: 'Bacterial stem rot risk — water the soil, never the crown.',
    },
    source: 'seed',
  },
  {
    name: 'Dracaena / Song of India (Karachi)',
    species: 'Dracaena reflexa',
    wateringSeasonal: { summer: 4, monsoon: 6, winter: 8 },
    fertilizeEveryDays: 45,
    fertilizer: 'Balanced feed; brown tips can be fluoride/chlorine — use stored water',
    repotEveryMonths: 30,
    pruningNotes: 'Top the cane to force branching; tops root as cuttings.',
    seasonalNotes: {
      heatWave: 'Bright indirect only; variegation fades in deep shade.',
      monsoon: 'Slow to dry — halve the watering you think it needs.',
    },
    source: 'seed',
  },
  {
    name: 'Curry Leaf (Karachi)',
    species: 'Murraya koenigii',
    wateringSeasonal: { summer: 2, monsoon: 5, winter: 6 },
    fertilizeEveryDays: 30,
    fertilizer: 'Iron-rich feed (yellowing between veins = iron deficiency, very common in pots)',
    repotEveryMonths: 24,
    pruningNotes: 'Pinch growing tips for bushiness; remove flower heads unless you want seed.',
    seasonalNotes: {
      heatWave: 'Loves Karachi heat with steady water; drops leaves in any cold snap.',
      monsoon: 'Citrus psyllid watch — curled distorted new leaves.',
    },
    source: 'seed',
  },
  {
    name: 'Lemon / Citrus (Karachi)',
    species: 'Citrus limon',
    wateringSeasonal: { summer: 2, monsoon: 5, winter: 4 },
    fertilizeEveryDays: 30,
    fertilizer: 'Citrus-special NPK with zinc & iron; feed Feb, Jun, Sep',
    repotEveryMonths: 24,
    pruningNotes: 'Remove water shoots and inward growth after harvest; keep center open.',
    seasonalNotes: {
      heatWave: 'Deep-water pots; fruit drop above 42°C is the tree protecting itself.',
      monsoon: 'Leaf miner tunnels in new flush — remove affected leaves, neem spray.',
    },
    source: 'seed',
  },
  {
    name: 'Mint (Karachi)',
    species: 'Mentha',
    wateringSeasonal: { summer: 1, monsoon: 2, winter: 2 },
    fertilizeEveryDays: 30,
    fertilizer: 'Compost top-dress; overfed mint loses flavor',
    repotEveryMonths: 12,
    pruningNotes: 'Cut back hard and often; it regrows from runners.',
    seasonalNotes: {
      heatWave: 'Afternoon shade or it cooks; never let the pot dry fully.',
      monsoon: 'Rust spots on leaves — cut to soil level, it regrows clean.',
    },
    source: 'seed',
  },
  {
    name: 'Kitchen garden vegetables (Karachi winter)',
    species: 'Seasonal vegetables',
    wateringSeasonal: { summer: 1, monsoon: 2, winter: 2 },
    fertilizeEveryDays: 15,
    fertilizer: 'Compost base + balanced NPK every 2 weeks once fruiting starts',
    repotEveryMonths: null,
    pruningNotes: 'Crop-specific: pinch tomato suckers, harvest okra young and often.',
    seasonalNotes: {
      heatWave: 'Oct–Feb is the season for tomato/spinach/broccoli/peas; summer belongs to okra, gourds, chilies.',
      monsoon: 'Seedlings drown easily — sow winter crops after the rains taper (late Sep).',
    },
    source: 'seed',
  },
];
